version: "3"
services:
  node-app:
    build: .
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=alaaDB
      - MONGO_INITDB_ROOT_PASSWORD=mongoPass